services:
  postgres:
    container_name: postgres
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: hackathonsforum
      POSTGRES_USER: hackathonsuser
      POSTGRES_PASSWORD: hackathonspassword
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped

volumes:
  postgres:
